spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/api-pedidos
    username: root
    password: admin123
  jpa:
    show-sql: true
  application:
    name: api-pedidos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 0
